#nanopore_gene_analysis.R
#this file is meant to be used inside Rstudio
#
#this script takes in methylation percentages, groups by gene level, calculates summary statistics, and draws a heatmap
#this file can be generated by bedtools:
#
#bedtools intersect -a gencode.v38.genes.sorted.bed -b P2574_3331A_modified_bases.5mC.sorted.bedgraph -wa -wb -sorted | awk '{print($0 "\tP2574_3331A")}' > P2574_3331A_modified_bases.5mC.sorted.genes.intersect.bed
#
#where:
#gencode.v38.genes.sorted.bed is the GENCODE v38 gene-level segments,
#P2574_3331A_modified_bases.5mC.sorted.bedgraph is a bedgraph of the modified_bases.5mC.bed from megalodon, filtered on column 5 > 0, and extracting only the chrom, start, end, and percent methylation columns
#
#multiple intersected bed files can be joined using cat, and fed into this script.

library(data.table)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(pheatmap)

#read and calculate gene-level average
genes_intersect <- fread("/mnt/ix1/Projects/M083_20211228_nanopore_methylation_GI/tissue_bank_CRC/04_deconv_with_plasma/merged.gene_summary.txt")
genes_intersect <- genes_intersect %>% mutate(type=ifelse(grepl("plas",V11),"Blood Center","Tissue Bank"))
genes_intersect_summary <- genes_intersect %>% group_by(V5,V6,V11,type) %>% summarize(m=mean(V10))

#filtration and calculate p-value
genes_intersect_summary <- genes_intersect_summary %>% 
  group_by(V5,V6) %>% 
  summarize(nb = sum(type=="Blood Center"), nt = sum(type=="Tissue Bank"), sd_b=sd(m[type=="Blood Center"]), sd_t=sd(m[type=="Tissue Bank"])) %>%
  filter(nb>1 & nt>1 & sd_b > 0 & sd_t > 0)

genes_intersect_pvalue <- genes_intersect %>% group_by(V5,V6,V11,type) %>% summarize(m=mean(V10)) %>% ungroup() %>% filter(V6 %in% genes_intersect_summary$V6) %>% group_by(V6) %>% summarize(
  p = t.test(m[type=="Blood Center"], m[type=="Tissue Bank"])$p.value, 
  c_b=sd(m[type=="Blood Center"], na.rm=T)/mean(m[type=="Blood Center"], na.rm=T),
  c_t=sd(m[type=="Tissue Bank"], na.rm=T)/mean(m[type=="Tissue Bank"], na.rm=T),
  m=mean(m[type=="Blood Center"], na.rm=T)- mean(m[type=="Tissue Bank"], na.rm=T))

#multiple testing correction and thresholding
genes_intersect_pvalue$qval <- p.adjust(genes_intersect_pvalue$p, method = "fdr")

genes_sig <- genes_intersect_pvalue %>% filter(qval < 0.01) %>% .$V6


#pivot to wide format and draw a heatmap
genes_intersect_mtx <- dcast(data = genes_intersect %>% group_by(V5,V6,V11,type) %>% summarize(m=mean(V10)) %>% ungroup() %>% filter(V6 %in% genes_sig) %>% filter(!grepl("pseudo|unprocessed|TEC|lncRNA|miRNA",V5)), formula = V6 ~ V11, value.var = "m") %>% as.data.frame()
rownames(genes_intersect_mtx) <- genes_intersect_mtx$V6
genes_intersect_mtx$V6 <- NULL

types <- data.frame(type=ifelse(as.numeric(grepl(pattern="plas",colnames(genes_intersect_mtx))),"Healthy","Cancer"))
rownames(types) <- colnames(genes_intersect_mtx)
lab_row <- data.frame(x=colnames(genes_intersect_mtx)) %>% separate(x, sep = "_", into = c("pat","sample")) %>% .$pat

pheatmap(t(genes_intersect_mtx), show_rownames = T, show_colnames = T, fontsize=20, cex=0.85, width=18, height=9, angle_col=45, annotation_row = types, labels_row = lab_row, filename="tb_genes_intersect4.png")
dev.off() #reset rstudio plotting otherwise ggplot stops working

#write table of significant genes
table_to_write <- genes_intersect_pvalue %>% filter(V6 %in% rownames(genes_intersect_mtx)) %>% select(V6,qval,m,c_b,c_t) %>% arrange(qval)
fwrite(table_to_write %>% select(V6,qval,m), "tb_genes_sig_3.txt", row.names = F, col.names = F, quote = F, sep="\t")

#look at CV of healthy vs cancer patient methylation for significant genes
table_to_write_melt <- melt(table_to_write, measure.vars=c("c_b","c_t"))
ggplot(table_to_write_melt, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot() +
  scale_x_discrete(labels=c("Healthy","Cancer")) +
  ylab("Methylation coefficient of variation\nper significant gene") +
  theme_classic(40) +
  theme(legend.position="none",
        axis.title.x = element_blank())

ggsave("CV_significant_genes.png", width=10, height=10, units="in", dpi=300)

t.test(table_to_write$c_b,table_to_write$c_t)

#plot methylation for a few genes of interest
genes_intersect_subset <- genes_intersect %>% group_by(V5,V6,V11,type) %>% summarize(m=mean(V10)) %>% ungroup() %>% filter(V6 %in% c("SPIB","CDCA7","CD79A","ENPP4","SLC25A1"))

ggplot(genes_intersect_subset, aes(x=V6, y=m, fill=type)) +
  geom_boxplot() +
  theme_classic(40) +
  ylab("% Methylation") +
  scale_fill_discrete(labels=c("Healthy","Cancer")) +
  geom_vline(xintercept = c(1.5,2.5,3.5,4.5,5.5), linetype="dashed") +
  theme(legend.position="top",
        legend.justification="left",
        legend.title = element_blank(),
        legend.text = element_text(size=25),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=45, hjust=1),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,-10,-10))

ggsave("tb_genes_selected_3_wide.png", dpi=300, height=9, width=12, units="in")

#look at dependence of CpG site coverage and methylation
genes_intersect_sites_cov <- genes_intersect %>% filter(V6 %in% rownames(genes_intersect_mtx) & V5 == "protein_coding") %>% group_by(V5,V6,V11,type) %>% summarize(m=mean(V10),n=n())

labels=c(
  "Blood Center"="Healthy",
  "Tissue Bank"="Cancer"
)

ggplot(genes_intersect_sites_cov, aes(x=m,y=n)) + 
  geom_point(size=3) +
  geom_density_2d() +
  scale_y_log10() +
  theme_classic(40) +
  xlab("Gene-level methylation") +
  ylab("CpG sites covered in gene") +
  theme(legend.position="none")

ggsave("tb_site_cov_correlation.png", dpi=300, width=10, height=10, units="in")


